---
- name: DOCKER AND NGINX FOR UBUNTU
  hosts: ubuntu
  become: yes

  tasks:
    - name: UPDATE APT PACKAGE CACHE
      ansible.builtin.apt:
        update_cache: yes

    - name: PREREQUISITE PACKGES
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: DOCKER'S OFFICIAL GPG KEY
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: DOCKER REPOSITORY
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: DOCKER ENGINE
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: DOCKER SDK FOR PYTHON
      ansible.builtin.apt:
        name: python3-docker
        state: present

    - name: START AND ENABLE DOCKER ON BOOT
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the latest Nginx image
      community.docker.docker_image:
        name: nginx
        source: pull

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "8080:80" #change mo nalang if occupied na ports mo T_T 
#nasa port 80:80 kasi Apache2 ko hehe
